Infographic
navikt/min-ia pull request #20
Opened 2022-03-09 09:09 UTC by Brunarspunar

![image](https://user-images.githubusercontent.com/17157469/157409497-c1a5bc2e-2a80-4b8b-b003-bffa426c6944.png)

2022-03-09 13:27 UTC, MalazAlkoj commented on client/jest.config.js
> +// jest.config.js
Burde vi fjerne kommentarer her?

2022-03-09 14:00 UTC, thomasdufourd commented on client/src/komponenter/Layout/Layout.tsx
> +import {Heading, Ingress} from "@navikt/ds-react";
Prettify?

2022-03-09 14:01 UTC, thomasdufourd commented on client/src/pages/api/organisasjoner.ts
> +import { AltinnOrganisasjon } from "../../integrasjoner/altinnorganisasjon-api";
Liker navnet `integrasjoner` ;)

2022-03-09 14:03 UTC, thomasdufourd commented on client/src/hooks/useSykefraværshistorikk.ts
> +  const orgnr = "910969439"; // TODO: Hent ut faktisk orgnr
Kan bruke en `useOrgnr()` (som vi gjorde i `sykefraværsstatistikk`). Den skal bare hente URL parameteren `orgnr`

2022-03-09 14:14 UTC, thomasdufourd commented on client/src/InfographicFlis/InfographicFlis.module.scss
> +}
Ved å bruke CSS property på SVG `transform: rotate(XXdeg);` kan vi få den pillen til å peke opp eller ned.
Som f.eks: 
 - "stigende" blir `  transform: rotate(45deg);`  
 - "senkende" blir `  transform: rotate(135deg);`

2022-03-09 14:15 UTC, thomasdufourd commented on client/src/InfographicFlis/InfographicFlis.module.scss
> +}
Denne kan ikke bruke direkte her, må være noe som bare gjelder pil ikonen

2022-03-09 14:16 UTC, thomasdufourd requested changes
Har et ønske om å bruke  `transform: rotate(XXdeg);` på pil ikonen  
![Screenshot 2022-03-09 at 15 19 11](https://user-images.githubusercontent.com/322962/157459952-43837f2a-cc6f-4300-8026-0747693a1481.png)
![Screenshot 2022-03-09 at 15 17 44](https://user-images.githubusercontent.com/322962/157459972-aed941a9-2401-40ed-9255-bacb40a4728f.png)

2022-03-10 10:06 UTC, Brunarspunar commented on client/jest.config.js
> +// jest.config.js
Done

2022-03-10 10:08 UTC, Brunarspunar commented on client/src/hooks/useSykefraværshistorikk.ts
> +  const orgnr = "910969439"; // TODO: Hent ut faktisk orgnr
Egen oppgave: https://trello.com/c/c57L2B5q

2022-03-10 10:08 UTC, Brunarspunar commented on client/src/InfographicFlis/InfographicFlis.module.scss
> +}
Malaz fiksa det :)

2022-03-10 10:59 UTC, merged

2022-03-10 11:30 UTC, MalazAlkoj approved these changes